### PR TITLE
Simplify loader menu

### PR DESCRIPTION
**Pull request by geoand**
Only provide a single option - to Install CentOS 7 and use it as a
default without having to wait for the 60 second timeout to elapse

### CODE REVIEW

**Comment by cmoulliard** [comment]
Can we resolve this issue and use `sed` ? I

**Comment by geoand** [comment]
I don't see why we should use sed, when we are there ones that get to
define the whole isolinux.cfg file in the first place 😀

**Comment by cmoulliard** [comment]
> sed

To avoid to have to maintain the `isolinux.cfg` file that I added to the project for the moment.

**Comment by geoand** [comment]
But we need to specify that file somehow, either inline with `cat` as you did previously or as a separate file. I don't see of any way to be able to forgo the file contents altogether

**Comment by cmoulliard** [comment]
As we copy/paste the `isolinux.cfg` file now, can you this PR please ?

**Comment by geoand** [comment]
I will update and test it locally before pushing :)

**Comment by cmoulliard** [comment]
We will not use/support kickstart for the moment as cloud-init do the job without less pain

**Pull request closed without merging**
